<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ISIPL-PUNV-L406.local" failures="1" tests="6" name="day11.AttributeDemoRetry" time="0.030" errors="0" timestamp="2024-11-14T22:04:48 IST" skipped="5">
  <testcase classname="day11.AttributeDemoRetry" name="testMethod" time="0.016">
    <skipped/>
  </testcase> <!-- testMethod -->
  <system-out/>
  <testcase classname="day11.AttributeDemoRetry" name="testMethod" time="0.002">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at day11.AttributeDemoRetry.testMethod(AttributeDemoRetry.java:11)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testMethod -->
  <system-out/>
  <testcase classname="day11.AttributeDemoRetry" name="testMethod" time="0.002">
    <skipped/>
  </testcase> <!-- testMethod -->
  <system-out/>
  <testcase classname="day11.AttributeDemoRetry" name="testMethod" time="0.001">
    <skipped/>
  </testcase> <!-- testMethod -->
  <system-out/>
  <testcase classname="day11.AttributeDemoRetry" name="testMethod" time="0.006">
    <skipped/>
  </testcase> <!-- testMethod -->
  <system-out/>
  <testcase classname="day11.AttributeDemoRetry" name="testMethod" time="0.003">
    <skipped/>
  </testcase> <!-- testMethod -->
  <system-out/>
</testsuite> <!-- day11.AttributeDemoRetry -->
